# Google Cloud Build configuration for Communication Assessment App
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/communication-assessment-app:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/communication-assessment-app:latest',
      '.'
    ]
    id: 'build-image'

  # Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/communication-assessment-app:$BUILD_ID'
    ]
    id: 'push-image-with-build-id'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/communication-assessment-app:latest'
    ]
    id: 'push-latest-image'
    waitFor: ['build-image']

  # Deploy to Cloud Run with secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'communication-assessment-app',
      '--image', 'gcr.io/$PROJECT_ID/communication-assessment-app:$BUILD_ID',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '2Gi',
      '--cpu', '4',
      '--max-instances', '20',
      '--min-instances', '1',
      '--timeout', '600',
      '--concurrency', '100',
      '--set-env-vars', 'NODE_ENV=production,AZURE_SPEECH_REGION=centralindia,EMAIL_HOST=smtp.gmail.com,EMAIL_PORT=587',
      '--set-secrets', 'MONGODB_URI=mongodb-uri:latest',
      '--set-secrets', 'SESSION_SECRET=session-secret:latest',
      '--set-secrets', 'OPENAI_API_KEY=openai-api-key:latest',
      '--set-secrets', 'DEEPSEEK_API_KEY=deepseek-api-key:latest',
      '--set-secrets', 'AZURE_SPEECH_KEY=azure-speech-key:latest',
      '--set-secrets', 'EMAIL_USER=email-user:latest',
      '--set-secrets', 'EMAIL_PASS=email-pass:latest',
      '--set-secrets', 'RAZORPAY_KEY_ID=razorpay-id:latest',
      '--set-secrets', 'RAZORPAY_KEY_SECRET=razorpay-secret:latest'
    ]
    id: 'deploy-to-cloud-run'
    waitFor: ['push-image-with-build-id']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/communication-assessment-app:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/communication-assessment-app:latest'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build (30 minutes)
timeout: '1800s'

# Substitutions for environment-specific values
substitutions:
  _REGION: 'us-central1'

  _SERVICE_NAME: 'communication-assessment-app'



